### ISSUE TITLE
Some packages from 3.9 fail to install

### ISSUE THREAD

**Issue by zgoda** [deadsnakes/issues#136]
### description

lib2to3 and distutils from 3.9 line fail to install. 3.8.5 is system-provided.

```
Preparing to unpack .../python3.9-lib2to3_3.9.0-1+focal2_all.deb ...
Unpacking python3.9-lib2to3 (3.9.0-1+focal2) ...
dpkg: error processing archive /var/cache/apt/archives/python3.9-lib2to3_3.9.0-1+focal2_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3.9/lib2to3/Grammar.txt', which is also in package python3-lib2to3 3.8.5-1~20.04.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../python3.9-distutils_3.9.0-1+focal2_all.deb ...
Unpacking python3.9-distutils (3.9.0-1+focal2) ...
dpkg: error processing archive /var/cache/apt/archives/python3.9-distutils_3.9.0-1+focal2_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3.9/distutils/README', which is also in package python3-distutils 3.8.5-1~20.04.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/python3.9-lib2to3_3.9.0-1+focal2_all.deb
 /var/cache/apt/archives/python3.9-distutils_3.9.0-1+focal2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

#### uname -a

```
Linux bekon 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
damn well, looks like upstream slipped their own python3.9 package late into focal which now conflicts with our packaging

this happened as well with python3.7 on bionic

**Comment by zgoda** [comment]
```
$ apt-cache show python3.9
Package: python3.9
Priority: optional
Section: python
Installed-Size: 529
Maintainer: Matthias Klose <doko@debian.org>
Architecture: amd64
Version: 3.9.0-1+focal2
Suggests: python3.9-venv, python3.9-doc, binutils
Depends: python3.9-minimal (= 3.9.0-1+focal2), libpython3.9-stdlib (= 3.9.0-1+focal2), mime-support
Filename: pool/main/p/python3.9/python3.9_3.9.0-1+focal2_amd64.deb
Size: 453680
MD5sum: 250505fd3b1ea3a6b1c661ac75221206
SHA1: 7e2866971f151662b8752ac2e86267bb987b5145
SHA256: 250dd5699546d2afd33ef7aa7acc73f968f485242b771b8b15b8e001c1a1aa30
Description-en: Interactive high-level object-oriented language (version 3.9)
 Python is a high-level, interactive, object-oriented language. Its 3.9 version
 includes an extensive class library with lots of goodies for
 network programming, system administration, sounds and graphics.
Description-md5: a49d415b9295004c3b3859dbe6873c2d
Multi-Arch: allowed

Package: python3.9
Architecture: amd64
Version: 3.9.0~rc1-1~20.04
Multi-Arch: allowed
Priority: optional
Section: universe/python
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Matthias Klose <doko@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 529
Depends: python3.9-minimal (= 3.9.0~rc1-1~20.04), libpython3.9-stdlib (= 3.9.0~rc1-1~20.04), mime-support
Suggests: python3.9-venv, python3.9-doc, binutils
Breaks: python3-all (<< 3.6.5~rc1-1), python3-dev (<< 3.6.5~rc1-1), python3-venv (<< 3.6.5-2)
Filename: pool/universe/p/python3.9/python3.9_3.9.0~rc1-1~20.04_amd64.deb
Size: 406164
MD5sum: 0e485941d24db25c017e9f57f32ef0c1
SHA1: 270b3af5bb419dfea0d2c11c6ac3c5ecf755b203
SHA256: a74b0b313ba2881017ddbc1c7c2cb20eda1f7245b7321005caeafdd07fdbda33
SHA512: df041bad40e8e6e09dc1e7bbdea1cc6b2c964f9a11322713db804d665fb31e98938d5160d40450b7356398bc3a3a4823774850d987dbb86cae3339dac3805bbb
Description-en: Interactive high-level object-oriented language (version 3.9)
 Python is a high-level, interactive, object-oriented language. Its 3.9 version
 includes an extensive class library with lots of goodies for
 network programming, system administration, sounds and graphics.
Description-md5: a49d415b9295004c3b3859dbe6873c2d
Phased-Update-Percentage: 60
```

**Comment by asottile** [comment]
yeah it's not a huge problem, I'll just need to factor out the supplemental packages from the 3.9 focal packaging as I did for 3.7 bionic

**Comment by sanderjo** [comment]
Just posting to say I experience the same on fresh Ubuntu 20.04 (fresh docker image). A solution or workaround would be nice. I don't see that posted, right?

```
Unpacking python3.9-lib2to3 (3.9.0-1+focal2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-ctgn9C/7-python3.9-lib2to3_3.9.0-1+focal2_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3.9/lib2to3/Grammar.txt', which is also in package python3-lib2to3 3.8.5-1~20.04.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package python3.9-distutils.
Preparing to unpack .../8-python3.9-distutils_3.9.0-1+focal2_all.deb ...
Unpacking python3.9-distutils (3.9.0-1+focal2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-ctgn9C/8-python3.9-distutils_3.9.0-1+focal2_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3.9/distutils/README', which is also in package python3-distutils 3.8.5-1~20.04.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /tmp/apt-dpkg-install-ctgn9C/7-python3.9-lib2to3_3.9.0-1+focal2_all.deb
 /tmp/apt-dpkg-install-ctgn9C/8-python3.9-distutils_3.9.0-1+focal2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt install python3.9 python3.9-distutils python3.9-dev -y' returned a non-zero code: 100
```

**Comment by asottile** [comment]
I'm working to apply a similar patch to the bionic one but it's a little tricky as their packaging changed from bionic -- you should be able to pin the rc1 version provided by upstream as a workaround

<sub>note that I'm currently doing this for free and at the moment I'm unemployed -- consider [sponsoring](https://github.com/sponsors/asottile) </sub>

**Comment by asottile** [comment]
this should be fixed within the hour, I've just uploaded a fix which stops buildint the -{distutils,tk,lib2to3,gdbm} packages which are now provided by upstream

**Comment by sanderjo** [comment]
> this should be fixed within the hour

It's now 2 hours after, and I tried, and still get the same (with a fresh Docker). I'll try again in the morning.

```
Unpacking python3.9-lib2to3 (3.9.0-1+focal2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-fYeyMC/7-python3.9-lib2to3_3.9.0-1+focal2_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3.9/lib2to3/Grammar.txt', which is also in package python3-lib2to3 3.8.5-1~20.04.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package python3.9-distutils.
Preparing to unpack .../8-python3.9-distutils_3.9.0-1+focal2_all.deb ...
Unpacking python3.9-distutils (3.9.0-1+focal2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-fYeyMC/8-python3.9-distutils_3.9.0-1+focal2_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3.9/distutils/README', which is also in package python3-distutils 3.8.5-1~20.04.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /tmp/apt-dpkg-install-fYeyMC/7-python3.9-lib2to3_3.9.0-1+focal2_all.deb
 /tmp/apt-dpkg-install-fYeyMC/8-python3.9-distutils_3.9.0-1+focal2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt install python3.9 python3.9-distutils python3.9-dev -y' returned a non-zero code: 100
```

**Comment by asottile** [comment]
you're probably missing an `apt-get update` -- the `+focal2` packages no longer exist

**Comment by sanderjo** [comment]
I think I don't understand what you mean. 

Here is the relevant part from the Dockerfile:

https://github.com/sanderjo/docker-sabnzbd3-python3.9/blob/master/Dockerfile#L11-L17

Am I missing something?

**Comment by asottile** [comment]
yeah -- this bit in the "docker best practices" shows what's wrong: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get

basically your `apt update` is a cached layer so it's going to use stale metadata -- you always want all of your `apt` operations in a single `RUN` instruction

I've been meaning to make a video about this but haven't gotten around to it 🤷

**Comment by sanderjo** [comment]
Wow, that worked! Thank you!

**Comment by webknjaz** [comment]
Sounds like the GitHub Action hits the same caching problem: https://github.com/deadsnakes/issues/issues/139
